spring:
  batch:
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local
    include: google, naver, kakao
  datasource:
    url: jdbc:mysql://43.201.97.229:3306/capston?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  messages:
    basename: errors
  mail:
    host: smtp.gmail.com
    port: 587
    username: kyoungsuk3254@gmail.com
    password: cnlgfpagxudlgjzl
    transport:
      protocol: smtp
    debug: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    default-encoding: UTF-8
  data:
    redis:
      host: 43.201.97.229
      port: 6379
      password: root
      cache:
        expiration-after-write-policy: 1h
    session:
      store-type: redis
  main:
    allow-bean-definition-overriding: true

cloud:
  aws:
    credentials:
      accessKey: AKIASZNLEKKPEYCUXU5N
      secretKey: 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
    s3:
      bucket: ks-capston
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret:
    key: 7J2064W467Kg7J207IWY7Lqg7ZSE7IiY6rCV7IOd67aE65Ok7ZmU7J207YyF7ZWY7IS47JqU7KKL7J2A7ZqM7IKs7JeQ66qo65GQ7Leo7JeF7ISx6rO17ZWY7Iuk6rGw652866+/7Iq164uI64uk65287J2067iM7IS47IWY65Ok7Ja07KO87IWU7ISc6rCQ7IKs7ZWp64uI64uk64+E7JuA7J2065CY7JeI7Jy866m07KKL6rKg7Iq164uI64uk

logging:
  level:
    org.hibernate.SQL: debug
server:
  shutdown: graceful
